# Generated by Django 4.2.20 on 2025-10-28 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='用例名称')),
                ('method', models.CharField(default='GET', max_length=10, verbose_name='请求方法')),
                ('path', models.CharField(max_length=500, verbose_name='接口路径')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='请求头')),
                ('body', models.JSONField(blank=True, default=dict, verbose_name='请求体')),
                ('config_elements', models.JSONField(blank=True, default=list, verbose_name='配置元件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project', verbose_name='所属项目')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
